// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knoyjjmjbpwpqschoyka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub3lqam1qYnB3cHFzY2hveWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzczMDMsImV4cCI6MjA2NzQxMzMwM30.kRH3bUicWQbLiZYtwJuQ92roZzIVU5K_CXuuklfQdPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});