// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sslopnjbkwehwjdzzkbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzbG9wbmpia3dlaHdqZHp6a2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzMxOTksImV4cCI6MjA2NzQwOTE5OX0.rCLvFMajl2dJATtvxfekJnoD8Wr3hHBduDA1kaRq04M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});